server:
  port: 8443
  ssl:
    enabled: true
    cert_file: ${SSL_CERT_FILE}
    key_file: ${SSL_KEY_FILE}
  timeout: 30s
  read_timeout: 15s
  write_timeout: 15s

services:
  auth:
    url: ${AUTH_SERVICE_URL}
    timeout: 5s
  user:
    url: ${USER_SERVICE_URL}
    timeout: 5s
  post:
    url: ${POST_SERVICE_URL}
    timeout: 5s

security:
  cors:
    enabled: true
    allowed_origins:
      - "https://yourdomain.com"
      - "http://localhost:3000"
    allowed_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
  rate_limit:
    enabled: true
    requests_per_second: 100