apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: social-network
  labels:
    app: social-network
    component: database
    tier: data
    managed-by: platform-team
  annotations:
    description: "PostgreSQL database credentials and configuration"
    last-modified: "2024-01-19"
    rotation-schedule: "90d"
type: Opaque
data:
  # Core Database Credentials (Base64 encoded)
  POSTGRES_USER: c29jaWFsdXNlcg== # socialuser
  POSTGRES_PASSWORD: c29jaWFscGFzcw== # socialpass
  POSTGRES_DB: c29jaWFsbmV0d29yaw== # socialnetwork
  DB_URL: cG9zdGdyZXNxbDovL3NvY2lhbHVzZXI6c29jaWFscGFzc0Bwb3N0Z3Jlczo1NDMyL3NvY2lhbG5ldHdvcms= # postgresql://socialuser:socialpass@postgres:5432/socialnetwork

  # Connection Pool Settings
  DB_MAX_CONNECTIONS: MjU= # 25
  DB_MIN_CONNECTIONS: NQ== # 5
  DB_MAX_IDLE_TIME: MzAwcw== # 300s

  # SSL/TLS Configuration
  DB_SSL_MODE: dmVyaWZ5LWZ1bGw= # verify-full
  DB_SSL_CERT: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t # Placeholder for actual certificate

  # Backup User Credentials
  BACKUP_USER: YmFja3VwX3VzZXI= # backup_user
  BACKUP_PASSWORD: YmFja3VwX3Bhc3N3b3Jk # backup_password

  # Read Replica Configuration
  READ_REPLICA_HOST: cG9zdGdyZXMtcmVhZA== # postgres-read
  READ_REPLICA_PORT: NTQzMg== # 5432
