apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
  namespace: social-network
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-reader
  namespace: social-network
rules:
- apiGroups: [ "" ]
  resources: [ "services", "endpoints" ]
  verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-gateway-service-reader
  namespace: social-network
subjects:
- kind: ServiceAccount
  name: api-gateway
  namespace: social-network
roleRef:
  kind: Role
  name: service-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: microservice
  namespace: social-network
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: config-reader
  namespace: social-network
rules:
- apiGroups: [ "" ]
  resources: [ "configmaps", "secrets" ]
  verbs: [ "get", "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: microservice-config-reader
  namespace: social-network
subjects:
- kind: ServiceAccount
  name: microservice
  namespace: social-network
roleRef:
  kind: Role
  name: config-reader
  apiGroup: rbac.authorization.k8s.io
