linters:
  enable:
  - gofmt
  - golint
  - govet
  - errcheck
  - staticcheck
  - gosimple
  - ineffassign
  - unconvert
  - misspell
  - gocyclo
  - gosec
  - prealloc

linters-settings:
  gocyclo:
    min-complexity: 15
  golint:
    min-confidence: 0.8
  gosec:
    excludes:
    - G404 # Insecure random number source (math/rand)

issues:
  exclude-rules:
  - path: _test\.go
    linters:
    - gocyclo
    - errcheck
    - dupl
    - gosec

run:
  deadline: 5m
  tests: true
  skip-dirs:
  - vendor/
  - third_party/

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
