# Server Configuration
server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: 10s
  write_timeout: 10s
  shutdown_timeout: 5s

# Database Configuration
database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "auth_service"
  sslmode: "disable"

# JWT Configuration
jwt:
  secret_key: "your-secret-key"
  expiration: 24h

# Logging Configuration
logging:
  level: "info"
  format: "json"

# Metrics Configuration
metrics:
  enabled: true
  path: "/metrics"

# Health Check Configuration
health:
  enabled: true
  path: "/health"
